// <auto-generated />
namespace Coe_Portal_Dashboard_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class acc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acc));
        
        string IMigrationMetadata.Id
        {
            get { return "202201181722468_acc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
